const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
test("language switching translates static and newly rendered content both ways",()=>{const core=fs.readFileSync(path.join(__dirname,"../assets/js/18-i18n.js"),"utf8");const complete=fs.readFileSync(path.join(__dirname,"../assets/js/25-i18n-complete.js"),"utf8");const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");assert.equal(core.includes('new CustomEvent("crm-language-changed"'),true);assert.equal(complete.includes("MutationObserver"),true);assert.equal(complete.includes("reverseTranslations"),true);assert.equal(complete.includes("reverseAttributeTranslations"),true);assert.equal(complete.includes('"Cotización":"Estimate"'),true);assert.ok(html.indexOf("18-i18n.js")<html.indexOf("25-i18n-complete.js"));});

test("every static Spanish interface phrase is covered by an i18n catalog",()=>{const core=fs.readFileSync(path.join(__dirname,"../assets/js/18-i18n.js"),"utf8");const complete=fs.readFileSync(path.join(__dirname,"../assets/js/25-i18n-complete.js"),"utf8");const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");const catalog=core+complete;const spanish=/[áéíóúñ¿¡]|\b(Agregar|Guardar|Nuevo|Nueva|Buscar|Todos|Todas|Sin|Control|Fecha|Precio|Costo|Material|Trabajo|Cliente|Pago|Gasto|Estado|Nombre|Notas|Cerrar|Cancelar|Pendiente|Resumen|Configuración|Proveedor|Compra|Instalación|Producción|Estimado|Ganancia|Saldo|Cobrado|Cuenta|Usuario|Empresa|Correo|Teléfono|Dirección|Responsable|Prioridad|Tipo|Cantidad|Unidad|Concepto|Categoría|Referencia|Semana|Período|Aplicar|Puedes|Solo|Eliminar|Restaurar)\b/;const texts=[...html.matchAll(/>([^<>]+)</g)].map(match=>match[1].replace(/\s+/g," ").trim()).filter(text=>text&&spanish.test(text));const missing=[...new Set(texts)].filter(text=>!catalog.includes(text));assert.deepEqual(missing,[]);});

test("every Spanish accessibility label is covered by an i18n catalog",()=>{const core=fs.readFileSync(path.join(__dirname,"../assets/js/18-i18n.js"),"utf8");const complete=fs.readFileSync(path.join(__dirname,"../assets/js/25-i18n-complete.js"),"utf8");const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");const catalog=core+complete;const labels=[...html.matchAll(/aria-label="([^"]+)"/g)].map(match=>match[1]);const spanish=/[áéíóúñ¿¡]|\b(Beneficios|Filtros|trabajos)\b/;const missing=[...new Set(labels.filter(label=>spanish.test(label)))].filter(label=>!catalog.includes(label));assert.deepEqual(missing,[]);});

test("dynamic modules can read the selected shared language",()=>{const core=fs.readFileSync(path.join(__dirname,"../assets/js/01-core.js"),"utf8");assert.equal(core.includes("window.state = state;"),true);});

test("salespeople and company settings stay bilingual after dynamic renders",()=>{const salespeople=fs.readFileSync(path.join(__dirname,"../assets/js/22-salespeople.js"),"utf8");const settings=fs.readFileSync(path.join(__dirname,"../assets/js/23-company-settings.js"),"utf8");const complete=fs.readFileSync(path.join(__dirname,"../assets/js/25-i18n-complete.js"),"utf8");assert.equal(salespeople.includes('function salespersonText(en, es)'),true);assert.equal(salespeople.includes('salespersonText("Pay commission", "Pagar comisión")'),true);assert.equal(salespeople.includes('window.addEventListener("crm-language-changed"'),true);assert.equal(settings.includes('function companySettingsText(en, es)'),true);assert.equal(settings.includes('window.addEventListener("crm-language-changed", renderCompanySettingsForm)'),true);assert.equal(complete.includes('"Identidad de la empresa":"Business identity"'),true);assert.equal(complete.includes('"Guardar configuración de empresa":"Save company settings"'),true);});

test("the selected language follows the signed-in account across devices",()=>{const app=fs.readFileSync(path.join(__dirname,"../assets/js/01-core.js"),"utf8");const auth=fs.readFileSync(path.join(__dirname,"../assets/js/11-auth.js"),"utf8");const i18n=fs.readFileSync(path.join(__dirname,"../assets/js/18-i18n.js"),"utf8");assert.equal(app.includes("platformAccount?.language"),true);assert.equal(app.includes("persistUserLanguagePreference"),true);assert.equal(app.includes("language: state.language"),true);assert.equal(auth.includes('window.setCrmLanguage(state.language, { persist: false })'),true);assert.equal(i18n.includes("window.persistUserLanguagePreference(next)"),true);assert.equal(i18n.includes("window.setCrmLanguage = setLanguage"),true);});
