const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const read=file=>fs.readFileSync(path.join(__dirname,"..",file),"utf8");
test("estimate and invoice emails use tenant identity and dedicated customer portals",()=>{const email=fs.readFileSync(path.join(__dirname,"../../functions/src/email.ts"),"utf8");assert.match(email,/from:brandedDocumentSender\(issuer\)/);assert.match(email,/estimate-review-public\.html/);assert.match(email,/invoice-view-public\.html/);assert.match(email,/sentPdfArtifactPath/);assert.doesNotMatch(email,/from:SENDER/)});
test("estimate portal is minimal, branded and preserves explicit electronic consent",()=>{const html=read("estimate-review-public.html"),js=read("estimate-review-public.js");assert.match(html,/id="companyLogo"/);assert.match(html,/id="acceptEstimateBtn"/);assert.match(html,/id="approvalConsent"/);assert.match(html,/id="completedEvidence"/);assert.match(js,/submitPublicEstimateApproval/);assert.match(js,/textContent/)});
test("invoice portal reviews the bill before handing payment to Stripe",()=>{const html=read("invoice-view-public.html"),js=read("invoice-view-public.js");assert.match(html,/id="viewInvoiceBtn"/);assert.match(html,/Pago protegido por Stripe/);assert.match(js,/createPublicInvoiceCheckout/);assert.match(js,/sessionStorage\.setItem\("signshopInvoiceReturn"/)});
test("accepted estimates fill one original page with date-only fields and a timed evidence strip",()=>{const source=fs.readFileSync(path.join(__dirname,"../../functions/src/estimate-approval.ts"),"utf8"),email=fs.readFileSync(path.join(__dirname,"../../functions/src/email.ts"),"utf8"),browser=read("assets/js/27-sales-documents.js");assert.match(browser,/__salesDocumentFieldLayout/);assert.match(email,/sentPdfFieldLayout/);assert.match(source,/fillOriginalDocumentFields/);assert.match(source,/evidence\.acceptedAtIso\.slice\(0,10\)/);assert.match(source,/Approval date and time \/ Fecha y hora/);assert.doesNotMatch(source,/pdf\.addPage\(\[612,792\]\)/);assert.match(source,/evidenceId=randomBytes/);assert.match(source,/approvalReceiptStatus:"sent"/);assert.match(source,/attachments:/)});
test("accepted estimates support full, partial and per-line invoice conversion",()=>{const html=read("index.html"),source=read("assets/js/27-sales-documents.js");for(const mode of ["full","partial","manual"])assert.match(html,new RegExp(`value="${mode}"`));assert.match(source,/conversionRatio/);assert.match(source,/convertedAmount:firebase\.firestore\.FieldValue\.increment/)});
test("partial conversions cannot exceed the remaining estimate balance",()=>{const source=read("assets/js/27-sales-documents.js");assert.match(source,/estimate\.convertedAmount/);assert.match(source,/remainingRatio/);assert.match(source,/requestedRatio>ratio/);assert.match(source,/alreadyConverted\+invoiceTotal>=estimateTotal-.01/)});
test("Stripe confirmation sends an idempotent tenant-branded PDF receipt",()=>{const source=fs.readFileSync(path.join(__dirname,"../../functions/src/stripe.ts"),"utf8");assert.match(source,/Payment received \/ Pago recibido/);assert.match(source,/stripe-receipt-\$\{eventId\}/);assert.match(source,/paymentReceiptStatus:"sent"/);assert.match(source,/paymentReceiptArtifactPath/);assert.match(source,/attachments:\[\{filename:/)});
test("paid invoices fill original fields and keep time only in the bottom paid strip",()=>{const source=fs.readFileSync(path.join(__dirname,"../../functions/src/stripe.ts"),"utf8");assert.match(source,/fillInvoicePaymentFields/);assert.match(source,/paidAtIso\.slice\(0,10\)/);assert.match(source,/PAID INVOICE \/ FACTURA PAGADA/);assert.match(source,/Payment date and time \/ Fecha y hora/);assert.match(source,/loadPrivateArtifact\(sourcePath\)/)});
